### ISSUE TITLE
down-center, ...

### ISSUE THREAD

**Issue by jotae1e** [evgmsk/ng3-tour#2]
May can you include "down-center", "left-down" and "right-down" in placement?

And the same on "top". 

Sometimes, the "tour" goes out of the main window.

Thanks

**Comment by jotae1e** [comment]
I implemented down-center and up-center, but I can't do a push because I changed some files to Spanish because https://github.com/evgmsk/ng3-tour/issues/1

Now, I can use your repo with the template.

I will do a push ASAP

Thanks for your work

**Comment by evgmsk** [comment]
I don't see any reason to add 'down-center'. The placement could be changed using CSS. So right-center and left-center are excess.

**Comment by jotae1e** [comment]
In fact, you are right. 
I know that I can use css to position the window, but with these properties it is calculated automatically. 
You are entitled to add them or not, of course, but the work is already done and they are very simple changes.
