### ISSUE TITLE
PrimeNg

### ISSUE THREAD

**Issue by jotae1e** [evgmsk/ng3-tour#3]
I am using PrimeNg. Some element are generated dynamically like tabs.  I can't put ngTourStep="", for example in all tabs.  I only can put one for the element, but I want to use more than one step.

I want to use your library with more than one step in same element with same name.  Something like:
```

 {
            stepName: "element",
            route: "home",
            title: 'My first lazily loaded feature',
            description: "My first feature description", 
            options: {backdrop: true}
        },
        {
            stepName: "element",
            route: "home",
            title: "My second lazily loaded feature",
            description: "My second feature description",
            options:{placement: 'top', smoothScroll: true}
        }
}
```

Can I did it?

Thanks

**Comment by evgmsk** [comment]
You can't use the same step name several times. You must use a unique "stepName" for every step! In your case, it may be 'element1', 'element2', et cetera.

**Comment by jotae1e** [comment]
Yes, I know it.  May be an enhancement.  I am using <div> tags to simulate.  

If you want, you can close the issue or label it.
