### ISSUE TITLE
Component out of the window

### ISSUE THREAD

**Issue by jotae1e** [evgmsk/ng3-tour#4]
Sometimes, if the component its at left of the window, the "tour" goes outside of the window, even if there is space on the right.

**Comment by evgmsk** [comment]
Sorry. I'm no wizarding. Please attach CSS and HTML code.

**Comment by jotae1e** [comment]
I will do a stackblitz repo in a few days, because I am in a middle of a project.

But I think that if you put a button in a page and do a simple step without options parameter, the box goes outside of the main window.

**Comment by evgmsk** [comment]
I tested the case you describe a lot of times and sure your problem has another ground.

**Comment by jotae1e** [comment]
May be that I using Prime NG components.  I will do more tests and I will report in this issue.  Thanks a lot.

**Comment by jotae1e** [comment]
I tried with this simple code in a component:  

```
<br>
<br>
<br>
<br>
<br>

<button ngTourStep="empleados_100" type="button">HOLA</button>
...
```

And this is the result:

<img width="1440" alt="captura" src="https://user-images.githubusercontent.com/7561881/76164015-84ff8080-614b-11ea-861b-9f69f8ddfa26.png">

**Comment by evgmsk** [comment]
You have a button on the left border of the layout without any margin and default placement 'down'. I don't understand, what do you want from me? You can change the placement of this step to 'right' or and left margin to your button.

**Comment by jotae1e** [comment]
In my modest opinion, if there is space on the right side of the screen, the window should adapt to that space, modifying the left property.

It is just an opinion.

It can be an enhancement.
