### ISSUE TITLE
targetResize

### ISSUE THREAD

**Issue by jotae1e** [evgmsk/ng3-tour#5]
How I can use target resize.  

I tried a lot of tests and none is working for me.

**Comment by evgmsk** [comment]
Sorry. I'm no wizarding. Please attach your code. I need to see arguments, that you pass to the method.

**Comment by jotae1e** [comment]
```
{
            stepName: "element",
            route: "home",
            title: 'My first lazily loaded feature',
            description: "My first feature description", 
            options: {
                   backdrop: true,
                   targetResize: [100, 200]
             }
}
```

**Comment by evgmsk** [comment]
Sorry and thanks. You find one more of my mistakes. I renamed this option but forgot to change instructions. Please name option stepTargetResize instead of targetResize.

**Comment by jotae1e** [comment]
Nice.  Awesome!!!!

I think that can be corrected in the README.md.
